name: json_extension_annotations
version: 0.1.0
author: svarzee <svarzee@gmail.com>
homepage: https://github.com/svarzee/json_extension
description: >-
  This package contains annotations which you can use for code generation with json_extension.
environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  class_extensions_annotations: ^0.1.0
