name: example

dependencies:
  class_extensions_annotations: ^0.1.0
  json_extension_annotations: ^0.2.0

dev_dependencies:
  build_runner: ^1.0.0
  class_extensions: ^0.3.0
  json_extension: ^0.1.0
  json_serializable: ^3.2.3