builders:
  dummy_extension_generators:
    import: "package:json_extension/json_extension.dart"
    builder_factories: ["jsonDummyBuilder"]
    build_extensions: {".dart": []}
    auto_apply: dependents
