name: json_extension
version: 0.4.1
author: svarzee <svarzee@gmail.com>
homepage: https://github.com/svarzee/json_extension
description: >-
  Uses class_extensions and json_serializable to generate methods for object serialization from/to json map/string.
environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  class_extensions: ^0.10.0
  json_extension_annotations: ^0.3.0
  analyzer: ^0.39.0
  build: '>=0.12.6 <2.0.0'
  source_gen: ^0.9.0

dev_dependencies:
  build_runner: ^1.0.0
